apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: hello-microshift

commonLabels:
  app.kubernetes.io/name: hello-microshift

namespace: demo

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
